# Generated by Django 3.2.20 on 2024-09-19 13:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserGameData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lives', models.IntegerField(default=5)),
                ('streak', models.IntegerField(default=0)),
                ('last_played', models.DateField(blank=True, null=True)),
                ('score', models.IntegerField(default=0)),
                ('levels_completed', models.IntegerField(default=0)),
                ('lives_reset_time', models.DateTimeField(blank=True, null=True)),
                ('footwear_levels', models.IntegerField(default=0)),
                ('clothing_levels', models.IntegerField(default=0)),
                ('bags_levels', models.IntegerField(default=0)),
                ('accessories_levels', models.IntegerField(default=0)),
                ('total_games_played', models.IntegerField(default=0)),
                ('total_games_won', models.IntegerField(default=0)),
                ('rank', models.CharField(default='Beginner', max_length=20)),
                ('CustomUser', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
